### ISSUE TITLE
Include vignettes dynamically into pkgdown

### ISSUE THREAD

**Issue by LukasWallrich** [mpru/karel#2]
You can sort and split up vignettes in pkgdown using the `articles` YAML section - so I would expect sth like this to work ... with that, you can use `usethis::use_pkgdown_github_pages()` and it should all build nicely automatically.

```
articles:
- title: Vignettes in English
  navbar: Vignettes in English
  contents:
  - one
  - two
  - three
- title: en espanol
  navbar: Vignettes in English
  contents:
   - uno
  - dos
  - tres
```
